### ISSUE TITLE
displayname in POST request sends empty string instead of rsn

### ISSUE THREAD

**Issue by LoggerBotThing** [ryanjpwatts/chat-channel-watcher#2]
After testing the plugin I noticed it wasn't sending any runescape names in the post request, I fixed this by putting a space in the player list widget field like this: https://i.imgur.com/Jo1gHAG.png . Afterwords it started to send the users names properly in the post request in the displayname field.  Perhaps this is because its written as String displayname; instead of String displayname = ""; in chatchannel event class. I could be wrong but I just had some minor troubles testing it out I thought it was because of not putting in the bearer token or something.

**Comment by ryanjpwatts** [comment]
Display name is always set in the constructor, it would be impossible to be null unless we're passing a null String as the argument when we instantiate our ChatChannelEvent.

Issue was an oversight with how I was handling previous name, see related commit: [f1a4fb5a7bed350a03a939eaa57fd4bb00970582](https://github.com/ryanjpwatts/chat-channel-watcher/commit/f1a4fb5a7bed350a03a939eaa57fd4bb00970582)

Will be fixed with next update, thank you :)
